### ISSUE TITLE
RSX repo not found

### ISSUE THREAD

**Issue by yaskhan** [nc4rrillo/indigo#1]
The repo http://github.com/nc4rillo/rsx deleted. Do you have a copy? You can upload to github?

**Comment by yaskhan** [comment]
Ah, you wrote in the Cargo file HTTP and not HTTPS. 
https://github.com/nc4rrillo/rsx  that link work :smile:

**Comment by nc4rrillo** [comment]
Thanks for reporting this. Fixed!
